### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by goranbrostrom** [yihui/Rd2roxygen#26]
In my old xxx.Rd I have

\author{\enc{Göran Broström}{George Bridgewater}}

where the second name is an English translation of my Swedish name. This becomes

#' @author \enc{Göran BroströmGeorge Bridgewater}

after Rd2roxygen, and 

\author{
\enc{Göran BroströmGeorge Bridgewater}
}

after devtools::document()

Not good. What can we do? Is the use of \enc{}{} obsolete?

Best, Göran/George/Yuri/Goran

**Comment by yihui** [comment]
Please see

https://github.com/yihui/Rd2roxygen/blob/0caa796ddbfa500d67239c9e221629ddeb793c1f/man/Rd2roxygen-package.Rd#L17-L28
